### ISSUE TITLE
Checkbox wasn't worked

### ISSUE THREAD

**Issue by Kengkat** [Kongpha/gms_template11#4]
I just see a checkbox in a setting window. But it doesn't work. Is it ready to use now?

**Comment by Kengkat** [comment]
Oh, I forgot to say, it isn't ready for using now. I will commit it when I build to finish. Sorry.

**Comment by gongpha** [comment]
Oh, I forgot to say, it isn't ready for using now. I will commit it when I build to finish. Sorry.

**Comment by gongpha** [comment]
Now, it is ready to use.
